version: "3"
services:
  frontend:
    build: frontend/.
  backend:
    build: denovote/.
    environment:
      DB_NAME: denovote
      DB_HOST_URL: mongo:27017
    restart: always
  mongo:
    image: mongo
  caddy:
    image: caddy:2.0.0-alpine
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - 4444:80
